### ISSUE TITLE
autowrap currently fails on 2.7 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/autowrap#112]
To reenable 2.7 support this might need some change
```
File "/home/runner/work/autowrap/autowrap/autowrap/PXDParser.py", line 142
   raise ValueError("Cannot parse '{}'".format(line)) from e
```

**Comment by jpfeuffer** [comment]
It is just the "raise .. from".
On one hand, we don't really need the functionality of "re-raising" (although it's nicer).
On the other hand, py 2.7 is long after end of life.

**Comment by jpfeuffer** [comment]
There would be a future package, too, but a dependency just for this.. hmm.. 
https://stackoverflow.com/questions/27318327/how-to-imitate-python-3s-raise-from-in-python-2

**Comment by timosachsenberg** [comment]
we basically dropped 2.7 support so I close this
