### ISSUE TITLE
Support `using` like we support `typedef`

### ISSUE THREAD

**Issue by poshul** [OpenMS/autowrap#146]
We currently don't handle `using` statements, these could at least initially be handled identically to ctypedef, and it would make writing code for wrapping slightly prettier.

**Comment by erik-whiting** [comment]
Howdy! I've been poking at this for the last few days in my spare time and have two questions.
First, does Cython have built in `using` support? I'm looking through the Cython code and I see `CTypeDefNode` for example, but no equivalent for `using`. I assume I will probably have to do something with the `AssignmentNode` maybe.

Can you tell me if this is a good test to start developing against?:
```python
def test_using_happy_path():
    decl1, decl2 = autowrap.PXDParser.parse_str(
      """
      cdef extern from "A.h":
        cusing myInteger = unsigned int;
        myInteger myInt;
      """
    )
    assert str(decl1.type) == 'unsigned int'
    assert decl2.name == 'myInt'
    assert str(decl2.type) == 'unsigned int'
```
This is my best guess at what you're looking for in this issue, am I on the right path?

**Comment by jpfeuffer** [comment]
Hey there!
I think you are right that Cython does not support using or cusing as a keyword.

@poshul Can you clarify the goal of this issue? Do you just want to be able to use using on the C++ side and be able to replicate the same in autowrap/Cython? If so, did you try to use using in C++ but ctypedef in the pxd? Or do you really want something like cusing in the pxd so they look similar (this would involve extending the Cython parser and I'm not sure if it is worth it).

@erik-whiting maybe for you it would be worthwhile to test the wrapping of using via ctypedef (and adding a test to autowrap). You would need to extend one of the tests that wraps a C++ class. Preferably the one that tests a typedef.

**Comment by poshul** [comment]
@jpfeuffer the goal was just to make the statements more similar between the C++ and PXD. If it's not trivial I don't think its worth doing.
