### ISSUE TITLE
Overloaded method docstrings don't indent properly

### ISSUE THREAD

**Issue by erik-whiting** [OpenMS/autowrap#157]
I noticed that the docstrings generated for overloaded methods leave the closing `"""` all the way to the left. I confirmed that this does **not** happen on all multiline docstrings; I made a `wrap-doc` directive with multiple lines and the indentation was fine.

Example:

`int_holder.hpp`:
```cpp
class IntHolder {
  public:
    int i_;
    int j_;
    IntHolder(int i): i_(i), j_(i * 2) {};
    IntHolder(const IntHolder &i): i_(i.i_), j_(i.j_) {};
    int add(const IntHolder &other) {
      return i_ + other.i_;
    }

    int someMethod() {
      return i_ + j_;
    }

    int someMethod(int k) {
      return i_ + j_ + k;
    }

    int someMethod(int k, int x) {
      return i_ + j_ + k + x;
    }
};

```
`int_holder.pxd`
```cython
cdef extern from "int_holder.hpp":
  cdef cppclass IntHolder:
    int i_
    int j_
    IntHolder(int i)
    IntHolder(IntHolder &i)
    int add(IntHolder o)
    int someMethod()
    int someMethod(int k)
    int someMethod(int k, int x)
```

Resulting `py_int_holder.pyx` file:
![image](https://user-images.githubusercontent.com/47164199/174699883-6c819cc2-d1d4-4ab2-8404-14007c7c489f.png)
Note the indentation on line 129

I think this is probably a good first issue or something easy for a beginner level programmer. If so, please label appropriately. If not, please assign to me. Thanks!

**Comment by jpfeuffer** [comment]
Should be mostly solved.
