### ISSUE TITLE
Seg Fault in certain processes of libcpp_test binding.

### ISSUE THREAD

**Issue by 24sharkS** [OpenMS/autowrap#93]
I generated extension module for libcpp_test.hpp script. While testing process211 as shown below, segmentation fault occurs. Similar situation also for process212 & process214.

![sf](https://user-images.githubusercontent.com/47356149/86399578-1d0a1280-bcc5-11ea-8622-6161ac805057.png)

Although, I understand that this error occurs as the function expects a dict with (b'42':non-empty list}) as atleast one key-value pair. 

```
 void  process211(std::map<int, float> & in, std::map<std::string, std::vector<int> > & arg2)
 {
     std::string test_str("42");
    in[1] = (float) arg2[test_str][0];
 }
```
Can cython gracefully handle the seg fault error ?

**Comment by uweschmitt** [comment]
No, you can not "catch" segfaults. The C++ code itself is "wrong" and you have to check the error conditon like

```
void  process211(std::map<int, float> & in, std::map<std::string, std::vector<int> > & arg2)
 {
     std::string test_str("42");
     if (arg2.contains(test_str))
         in[1] = (float) arg2[test_str][0];
 }
```
