### ISSUE TITLE
Question about `wrap-attach` vs `@staticmethod`

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/autowrap#94]
Hi @hroest and @uweschmitt 

Is there a reason why attaching a free function to a class was chosen over the `@staticmethod` decorator?
Or was this feature not present when support for static methods was required.

We are having problems like the following when building with the compiler directive `binding=True` (the new default in Cython3):
`unbound method "cython_function_or_method" object must be called with instance as first argument`

**Comment by timosachsenberg** [comment]
might be solved by the linked PR.
